### ISSUE TITLE
Some issues with demo game

### ISSUE THREAD

**Issue by jpcompton** [kaelhem/moiki-exporter#2]
I downloaded the .z5 sample game from http://klm-labs.com/nerding/inform/la-balade-en-foret.z5 and ran a couple of local tests.

In Frotz (v2.52 OSX Curses) I get “object#x” output that doesn’t show up in Parchment, and in Ozmoo (Commodore 64, generated by Ozmoo Online, image attached) I get Choix non reconnu, veuillez recommencer. even for valid input, which seems relevant since “a ton of retro computers” is mentioned as one of the points of I6 output.

In Ozmoo, it rejects the regular 1/2 numbers until it gets a different kind of invalid input. Simply entering >a is enough to fix the problem and allow the game to continue. However, the game will later crash with a stack full (Ozmoo fatal error #6) message. Boot the attached zipped .d64 in VICE or similar Commodore 64 emulator to explore.

[la-balade-en-foret.d64.zip](https://github.com/kaelhem/moiki-exporter/files/5204518/la-balade-en-foret.d64.zip)

**Comment by kaelhem** [comment]
Thanks for the report!
I've made a few changes in order to fix the error where "object#x" is displayed, but I have not tested on Frotz yet.
The demo file is updated, if you want to give a shoot.

The Ozmoo bug with the first key pressed is really weird, and the fatal error #6 is embarrassing... I need to investigate, but all of this is a completely new world for me.

Edit: I've tested on Frotz... the issue is still there...

**Comment by kaelhem** [comment]
I've updated the converter and the demo, and now, room identifiers (the "object#x") are not displayed anymore on Frotz.

For the other point, In order to target C64, I think I should make an export ready to be compiled with [puny-inform](https://github.com/johanberntsson/PunyInform)... I'm studying the case, stay tuned!

**Comment by jpcompton** [comment]
Compiling with Puny may well help!

If you're looking for other ways to generate a lightweight Z-machine binary, the choice framework for ZIL being used on these converted gamebooks might be of interest:

https://github.com/daelsepara/secret-knights
https://github.com/daelsepara/war-torn-kingdom
https://github.com/daelsepara/heart-of-ice

(he's got a few others as well, but this represents the different brands of gamebooks he's converted so far)

**Comment by jpcompton** [comment]
This is more of a functionality note than a bug: the game-over message doesn't mention UNDO, but UNDO is in fact supported. So you might want to either mention UNDO, or disable UNDO.

**Comment by jpcompton** [comment]
...also, it's even possible to get the stack overflow in Frotz. (And yes, this is with the newer version of the demo game, 89088 bytes, md5 9f1b0c9b71d558c995ff5516e6953dc8 )

<img width="1057" alt="Screen Shot 2020-09-11 at 10 04 28 AM" src="https://user-images.githubusercontent.com/51372049/92941781-6b9b0200-f416-11ea-887b-104c7bdf0076.png">

**Comment by kaelhem** [comment]
Thanks for the links, I will have a look.
For the stack overflow issues, I have a few ideas to try.

**Comment by kaelhem** [comment]
In order to make it works flawlessly, I've made a lot of changes.
Now, the script doesn't include any library and it can be compiled under versions 3 and 5 of z-machine.
Also, I've made some tests with ozmoo and all seems good on a C64 emulator.

I converted and compiled another story with the new format, you can have a look here :
http://iplayif.com/?story=http://klm-labs.com/nerding/inform/le-dino-park.z3
http://iplayif.com/?story=http://klm-labs.com/nerding/inform/le-dino-park.z5

**Comment by jpcompton** [comment]
Looks good so far, and compiling to .z3 when possible certainly makes it even more universal.

It's a little unusual to require the Enter key (and not accept any other key) to advance past the pause, but not unacceptable.

**Comment by kaelhem** [comment]
I was not aware of this! I've change the way it works to accept any key on the "wait" function (but only for v5 version, as it seems unfeasable in v3...).
I'm closing this ticket, but do not hesitate to re-open it (or a new one) if you encounter other issues
